import { StyleSheet } from 'react-native';

export const aiCheckerStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#F8FAFC',
    padding: 20,
  },
  scrollContainer: {
    flexGrow: 1,
  },
  header: {
    marginTop: 15,
    marginBottom: 25,
    alignItems: 'center',
  },
  title: {
    fontSize: 28,
    fontWeight: '800',
    color: '#1E293B',
    textAlign: 'center',
    letterSpacing: -0.5,
  },
  subtitle: {
    fontSize: 16,
    color: '#64748B',
    textAlign: 'center',
    marginTop: 8,
    fontWeight: '500',
    lineHeight: 22,
  },
  disclaimer: {
    backgroundColor: '#FEF3C7',
    borderColor: '#F59E0B',
    borderWidth: 1,
    borderRadius: 12,
    padding: 15,
    marginBottom: 25,
  },
  disclaimerText: {
    fontSize: 14,
    color: '#92400E',
    textAlign: 'center',
    fontWeight: '600',
    lineHeight: 18,
  },
  section: {
    marginBottom: 25,
  },
  sectionTitle: {
    fontSize: 20,
    fontWeight: '700',
    color: '#1E293B',
    marginBottom: 15,
  },
  symptomsGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
  },
  symptomCard: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    borderWidth: 2,
    borderColor: '#E2E8F0',
    borderRadius: 15,
    padding: 12,
    marginBottom: 10,
    minWidth: '45%',
    shadowColor: '#64748B',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  symptomCardSelected: {
    backgroundColor: '#EBF8FF',
    borderColor: '#3B82F6',
    shadowColor: '#3B82F6',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 8,
    elevation: 6,
  },
  symptomEmoji: {
    fontSize: 20,
    marginRight: 8,
  },
  symptomText: {
    fontSize: 14,
    fontWeight: '600',
    color: '#475569',
    flex: 1,
  },
  symptomTextSelected: {
    color: '#1E40AF',
    fontWeight: '700',
  },
  customInputContainer: {
    marginTop: 15,
  },
  customInputLabel: {
    fontSize: 16,
    fontWeight: '600',
    color: '#1E293B',
    marginBottom: 10,
  },
  customInput: {
    backgroundColor: '#FFFFFF',
    borderWidth: 2,
    borderColor: '#E2E8F0',
    borderRadius: 12,
    padding: 15,
    fontSize: 16,
    color: '#1E293B',
    minHeight: 80,
    textAlignVertical: 'top',
    shadowColor: '#64748B',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  severityContainer: {
    marginTop: 20,
  },
  severityTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: '#1E293B',
    marginBottom: 15,
  },
  severityButtons: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 10,
  },
  severityButton: {
    flex: 1,
    padding: 15,
    borderRadius: 12,
    borderWidth: 2,
    borderColor: '#E2E8F0',
    backgroundColor: '#FFFFFF',
    alignItems: 'center',
    shadowColor: '#64748B',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  severityButtonSelected: {
    borderColor: '#EF4444',
    backgroundColor: '#FEF2F2',
    shadowColor: '#EF4444',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 8,
    elevation: 6,
  },
  severityButtonMild: {
    borderColor: '#10B981',
    backgroundColor: '#F0FDF4',
  },
  severityButtonModerate: {
    borderColor: '#F59E0B',
    backgroundColor: '#FFFBEB',
  },
  severityButtonSevere: {
    borderColor: '#EF4444',
    backgroundColor: '#FEF2F2',
  },
  severityText: {
    fontSize: 14,
    fontWeight: '600',
    color: '#475569',
  },
  severityTextSelected: {
    fontWeight: '700',
  },
  severityTextMild: {
    color: '#059669',
  },
  severityTextModerate: {
    color: '#D97706',
  },
  severityTextSevere: {
    color: '#DC2626',
  },
  analyzeButton: {
    backgroundColor: '#3B82F6',
    borderRadius: 15,
    padding: 18,
    alignItems: 'center',
    marginTop: 30,
    marginBottom: 20,
    shadowColor: '#3B82F6',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.3,
    shadowRadius: 12,
    elevation: 8,
  },
  analyzeButtonDisabled: {
    backgroundColor: '#9CA3AF',
    shadowColor: '#9CA3AF',
  },
  analyzeButtonText: {
    color: '#FFFFFF',
    fontSize: 18,
    fontWeight: '700',
  },
  resultContainer: {
    backgroundColor: '#FFFFFF',
    borderRadius: 20,
    padding: 20,
    marginTop: 20,
    shadowColor: '#64748B',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.15,
    shadowRadius: 12,
    elevation: 8,
  },
  resultTitle: {
    fontSize: 22,
    fontWeight: '700',
    color: '#1E293B',
    textAlign: 'center',
    marginBottom: 15,
  },
  riskLevel: {
    padding: 15,
    borderRadius: 12,
    marginBottom: 20,
    alignItems: 'center',
  },
  riskLevelLow: {
    backgroundColor: '#F0FDF4',
    borderColor: '#10B981',
    borderWidth: 2,
  },
  riskLevelModerate: {
    backgroundColor: '#FFFBEB',
    borderColor: '#F59E0B',
    borderWidth: 2,
  },
  riskLevelHigh: {
    backgroundColor: '#FEF2F2',
    borderColor: '#EF4444',
    borderWidth: 2,
  },
  riskText: {
    fontSize: 18,
    fontWeight: '700',
    marginBottom: 5,
  },
  riskTextLow: {
    color: '#059669',
  },
  riskTextModerate: {
    color: '#D97706',
  },
  riskTextHigh: {
    color: '#DC2626',
  },
  riskDescription: {
    fontSize: 14,
    textAlign: 'center',
    fontWeight: '500',
  },
  riskDescriptionLow: {
    color: '#065F46',
  },
  riskDescriptionModerate: {
    color: '#92400E',
  },
  riskDescriptionHigh: {
    color: '#991B1B',
  },
  recommendationsTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: '#1E293B',
    marginBottom: 15,
  },
  recommendation: {
    flexDirection: 'row',
    marginBottom: 12,
    alignItems: 'flex-start',
  },
  recommendationBullet: {
    fontSize: 16,
    color: '#3B82F6',
    marginRight: 10,
    marginTop: 2,
  },
  recommendationText: {
    fontSize: 15,
    color: '#475569',
    flex: 1,
    lineHeight: 20,
    fontWeight: '500',
  },
  emergencyButton: {
    backgroundColor: '#EF4444',
    borderRadius: 12,
    padding: 15,
    alignItems: 'center',
    marginTop: 20,
    shadowColor: '#EF4444',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 6,
  },
  emergencyButtonText: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: '700',
  },
  consultButton: {
    backgroundColor: '#10B981',
    borderRadius: 12,
    padding: 15,
    alignItems: 'center',
    marginTop: 15,
    shadowColor: '#10B981',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 6,
  },
  consultButtonText: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: '700',
  },
  resetButton: {
    backgroundColor: '#6B7280',
    borderRadius: 12,
    padding: 15,
    alignItems: 'center',
    marginTop: 15,
    marginBottom: 30,
  },
  resetButtonText: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: '600',
  },
});