import { StyleSheet } from "react-native";

export const Availavilitystyle = StyleSheet.create({
  container: { flex: 1, backgroundColor: "#FFFFFF" },
  header: {
    flexDirection: "row",
    justifyContent: "center",
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: "#F0F0F0",
  },
  headerTitle: { fontSize: 18, fontWeight: "600", color: "#333" },
  content: { flex: 1 },
  calendarContainer: { padding: 25 },
  calendarHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 20,
  },
  navButton: { fontSize: 20, fontWeight: "600", color: "#333" },
  monthText: { fontSize: 18, fontWeight: "600", color: "#333" },
  dayHeaderRow: {
    flexDirection: "row",
    justifyContent: "space-around",
    marginBottom: 16,
  },
  dayHeader: {
    fontSize: 14,
    fontWeight: "500",
    color: "#666",
    width: 32,
    textAlign: "center",
  },
  calendarGrid: { flexDirection: "row", flexWrap: "wrap" },
  dayCell: {
    width: "14.28%",
    aspectRatio: 1,
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 8,
  },
  selectedDay: { backgroundColor: "#FF7A00", borderRadius: 20 },
  dayText: { fontSize: 16, color: "#333", fontWeight: "500" },
  selectedDayText: { color: "#FFFFFF", fontWeight: "600" },
  timeSlotsSection: { paddingLeft: 25 ,paddingRight:25},
  sectionTitle: {
    fontSize: 18,
    fontWeight: "600",
    color: "#333",
  },
  timeSlotRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingVertical: 16,
    paddingTop:15,
    paddingBottom:15,
    borderBottomWidth: 1,
    borderBottomColor: "#F5F5F5",
  },
  timeSlotText: { fontSize: 16, color: "#333", fontWeight: "500" },
  switch: { transform: [{ scaleX: 0.9 }, { scaleY: 0.9 }] },
  saveButton: {
    backgroundColor: "#FF7A00",
    margin: 16,
    paddingVertical: 14,
    borderRadius: 8,
    alignItems: "center",
  },
  saveButtonText: {
    color: "#fff",
    fontSize: 16,
    fontWeight: "600",
  },
});