import { StyleSheet } from 'react-native';
export const bookSLotstyles = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#F8F9FA' },
  profileCard: {
    position: 'relative',
    backgroundColor: '#fff',
    marginHorizontal: 16,
    marginTop: 20,
    borderRadius: 16,
    elevation: 4,
    shadowColor: '#000',
    shadowOpacity: 0.1,
    shadowOffset: { width: 0, height: 2 },
    shadowRadius: 8,
  },
  profileImage: {
    top: 30,
    left: 20,
    width: 120,
    height: 100,
    borderRadius: 5,
    marginBottom: 12,
    position: 'absolute',
  },
  ratingBadge: {
    position: 'absolute',
    top: 100,
    left: 25,
    backgroundColor: '#4CAF50',
    borderRadius: 12,
    paddingHorizontal: 8,
    paddingVertical: 4,
    flexDirection: 'row',
    alignItems: 'center',
  },
  ratingText: { color: '#fff', fontSize: 14, fontWeight: 'bold', marginLeft: 2 },
  specialityContainer: { flexDirection: 'row', alignItems: 'center', marginBottom: 12 },
  specialityText: { fontSize: 14, color: '#FF6B35', marginLeft: 8, fontWeight: '500' },
  nameContainer: { marginBottom: 12 },
  doctorName: { fontSize: 20, fontWeight: 'bold', color: '#333', marginBottom: 4 },
  statusContainer: { flexDirection: 'row', alignItems: 'center' },
  statusDot: { width: 8, height: 8, borderRadius: 4, marginRight: 6 },
  statusText: { fontSize: 14, color: '#4CAF50', fontWeight: '500' },
  infoRow: { flexDirection: 'row', alignItems: 'center', marginBottom: 8 },
  infoText: { fontSize: 14, color: '#666', marginLeft: 8 },
  creditsContainer: { marginTop: 12, paddingTop: 12, borderTopWidth: 1, borderTopColor: '#F0F0F0' },
  creditsLabel: { fontSize: 14, color: '#666', marginBottom: 4 },
  creditsRate: { fontSize: 16, fontWeight: 'bold', color: '#4285F4' },
  statsContainer: {
    backgroundColor: '#fff',
    marginHorizontal: 16,
    marginTop: 16,
    borderRadius: 16,
    padding: 20,
    elevation: 4,
    shadowColor: '#000',
    shadowOpacity: 0.1,
    shadowOffset: { width: 0, height: 2 },
    shadowRadius: 8,
  },
  statsTitle: { fontSize: 16, fontWeight: '600', color: '#333', marginBottom: 16 },
  statsGrid: { flexDirection: 'row', justifyContent: 'space-between' },
  statCard: {
    flex: 1,
    backgroundColor: '#F8F9FA',
    borderRadius: 12,
    padding: 16,
    alignItems: 'center',
    marginHorizontal: 4,
  },
  statIcon: { marginBottom: 8 },
  statLabel: { fontSize: 12, color: '#666', textAlign: 'center', marginBottom: 4 },
  statValue: { fontSize: 16, fontWeight: 'bold', color: '#333' },
  scheduleContainer: {
    backgroundColor: '#fff',
    marginHorizontal: 16,
    marginTop: 16,
    borderRadius: 16,
    padding: 20,
    elevation: 4,
    shadowColor: '#000',
    shadowOpacity: 0.1,
    shadowOffset: { width: 0, height: 2 },
    shadowRadius: 8,
  },
  scheduleTitle: { fontSize: 16, fontWeight: '600', color: '#333', marginBottom: 8 },
  scheduleSubtitle: { fontSize: 14, color: '#666', marginBottom: 20 },
  sectionTitle: { fontSize: 14, fontWeight: '600', color: '#333', marginBottom: 12 },
  datesContainer: { flexDirection: 'row', marginBottom: 24 },
  dateCard: {
    flex: 1,
    backgroundColor: '#F8F9FA',
    borderRadius: 12,
    padding: 12,
    alignItems: 'center',
    marginHorizontal: 4,
    borderWidth: 1,
    borderColor: '#E0E0E0',
  },
  dateCardSelected: { backgroundColor: '#4285F4', borderColor: '#4285F4' },
  dayText: { fontSize: 12, color: '#666', marginBottom: 4 },
  dayTextSelected: { color: '#fff' },
  dateText: { fontSize: 14, fontWeight: '600', color: '#333', marginBottom: 4 },
  dateTextSelected: { color: '#fff' },
  slotsText: { fontSize: 10, color: '#4285F4' },
  timeSlotsContainer: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
  timeSlot: {
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderRadius: 8,
    backgroundColor: '#F8F9FA',
    borderWidth: 1,
    borderColor: '#E0E0E0',
    minWidth: 80,
    alignItems: 'center',
  },
  timeSlotSelected: { backgroundColor: '#4285F4', borderColor: '#4285F4' },
  timeSlotText: { fontSize: 14, color: '#333', fontWeight: '500' },
  timeSlotTextSelected: { color: '#fff' },
  bottomContainer: {
    backgroundColor: '#fff',
    paddingHorizontal: 16,
    paddingVertical: 16,
    elevation: 8,
    shadowColor: '#000',
    shadowOpacity: 0.1,
    shadowOffset: { width: 0, height: -2 },
    shadowRadius: 8,
  },
  bookButton: {
    backgroundColor: '#F97316',
    paddingVertical: 16,
    borderRadius: 12,
    alignItems: 'center',
  },
  bookButtonText: { color: '#fff', fontSize: 16, fontWeight: '600' },
  
});