import { StyleSheet } from "react-native";


export const patientFullDetailsStyle = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: "#f8f9fa",
    },
    header: {
        flexDirection: "row",
        alignItems: "center",
        padding: 20,
        backgroundColor: "#fff",
        borderBottomWidth: 1,
        borderBottomColor: "#e9ecef",
    },
    backButton: {
        marginBottom: 10,
        fontSize:26,
        marginRight:10,
        fontWeight:600
    },
    backButtonText: {
        color: "#FF6B00",
        fontSize: 16,
        fontWeight: "600",
        justifyContent:"center"
    },
    headerTitle: {
        fontSize: 20,
        fontWeight: "700",
        color: "#333",
    },
    mainCard: {
        backgroundColor: "#fff",
        margin: 20,
        borderRadius: 15,
        padding: 20,
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 8,
        elevation: 4,
    },
    cardHeader: {
        flexDirection: "row",
        justifyContent: "space-between",
        alignItems: "flex-start",
    },
    clinicName: {
        fontSize: 22,
        fontWeight: "700",
        color: "#333",
        marginBottom: 5,
    },
    visitDate: {
        fontSize: 16,
        color: "#666",
        marginBottom: 5,
    },
    visitType: {
        fontSize: 18,
        color: "#555",
        fontWeight: "500",
        marginBottom: 8,
    },
    patientName: {
        fontSize: 14,
        color: "#FF6B00",
        fontWeight: "600",
    },
    statusBadge: {
        backgroundColor: "#e8f5e8",
        paddingHorizontal: 12,
        paddingVertical: 6,
        borderRadius: 20,
        borderWidth: 1,
        borderColor: "#4CAF50",
    },
    statusText: {
        color: "#2E7D32",
        fontWeight: "600",
        fontSize: 14,
    },
    section: {
        marginHorizontal: 20,
        marginBottom: 20,
    },
    sectionTitle: {
        fontSize: 20,
        fontWeight: "700",
        color: "#333",
        marginBottom: 15,
    },
    vitalsGrid: {
        flexDirection: "row",
        flexWrap: "wrap",
        justifyContent: "space-between",
    },
    vitalCard: {
        backgroundColor: "#fff",
        width: "48%",
        padding: 15,
        borderRadius: 12,
        marginBottom: 10,
        alignItems: "center",
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
        elevation: 2,
    },
    vitalLabel: {
        fontSize: 14,
        color: "#666",
        marginBottom: 5,
        textAlign: "center",
    },
    vitalValue: {
        fontSize: 18,
        fontWeight: "700",
        color: "#FF6B00",
        textAlign: "center",
    },
    vitalPrecision: {
        fontSize: 12,
        color: "#888",
        marginTop: 2,
        textAlign: "center",
    },
    detailsCard: {
        backgroundColor: "#fff",
        borderRadius: 12,
        padding: 20,
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
        elevation: 2,
    },
    detailRow: {
        flexDirection: "row",
        justifyContent: "space-between",
        alignItems: "flex-start",
        paddingVertical: 12,
        borderBottomWidth: 1,
        borderBottomColor: "#f1f3f4",
    },
    detailLabel: {
        fontSize: 16,
        color: "#555",
        fontWeight: "500",
        flex: 1,
    },
    detailValueContainer: {
        flex: 1,
        alignItems: "flex-end",
    },
    detailValue: {
        fontSize: 16,
        color: "#333",
        fontWeight: "600",
        textAlign: "right",
    },
    precisionText: {
        fontSize: 12,
        color: "#888",
        textAlign: "right",
        marginTop: 2,
    },
    medicationItem: {
        backgroundColor: "#f8f9fa",
        padding: 15,
        borderRadius: 8,
        marginBottom: 12,
        borderLeftWidth: 3,
        borderLeftColor: "#FF6B00",
    },
    medicationHeader: {
        flexDirection: "row",
        justifyContent: "space-between",
        alignItems: "center",
        marginBottom: 8,
    },
    medicationName: {
        fontSize: 18,
        fontWeight: "700",
        color: "#333",
    },
    medicationDosage: {
        fontSize: 16,
        fontWeight: "600",
        color: "#FF6B00",
    },
    medicationDetails: {
        flexDirection: "row",
        justifyContent: "space-between",
        alignItems: "center",
    },
    medicationTiming: {
        fontSize: 14,
        color: "#666",
        fontWeight: "500",
    },
    medicationInstruction: {
        fontSize: 14,
        color: "#666",
        fontStyle: "italic",
    },
    notesCard: {
        backgroundColor: "#fff",
        borderRadius: 12,
        padding: 20,
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
        elevation: 2,
    },
    notesText: {
        fontSize: 16,
        color: "#555",
        lineHeight: 24,
        fontStyle: "italic",
    },
    actionButtons: {
        flexDirection: "row",
        justifyContent: "space-between",
        margin: 20,
        marginBottom: 40,
    },
    downloadBtn: {
        backgroundColor: "#FF6B00",
        flex: 1,
        marginRight: 10,
        padding: 15,
        borderRadius: 12,
        alignItems: "center",
        shadowColor: "#FF6B00",
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.3,
        shadowRadius: 4,
        elevation: 3,
    },
    downloadBtnText: {
        color: "#fff",
        fontSize: 16,
        fontWeight: "600",
    },
    shareBtn: {
        backgroundColor: "#fff",
        flex: 1,
        marginLeft: 10,
        padding: 15,
        borderRadius: 12,
        alignItems: "center",
        borderWidth: 2,
        borderColor: "#FF6B00",
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
        elevation: 2,
    },
    shareBtnText: {
        color: "#FF6B00",
        fontSize: 16,
        fontWeight: "600",
    },
  
});